apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.backend.pvcName }}
spec:
  accessModes:
  - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
